### ISSUE TITLE
Bucket slug

### ISSUE THREAD

**Issue by neefrehman** [kemiljk/better-logos-figma#1]
hey @kemiljk, just trying to check if the cosmic client is working fine but I'm getting the following response whenever I try to query:

```shell
{ message: 'Route not found' }
```

Is the below bucket slug correct? Or maybe there's an error in my query. You can open this branch and run `npm run upload:assets` to see what I mean.

https://github.com/kemiljk/better-logos-figma/blob/3b8e0ed0d20395426d96fad07d0c01d8ca23dda9/scripts/upload-assets.ts#L9

**Comment by kemiljk** [comment]
Ahhh, so for the slug you can reduce it down to just the segment in-between `buckets/` and `/objects` so the slug should just be `better-logos-production`

**Comment by neefrehman** [comment]
perfect! that works great. thanks :)
