### ISSUE TITLE
Logos not rendering in UI

### ISSUE THREAD

**Issue by kemiljk** [kemiljk/better-logos-figma#28]
@neefrehman since the split the images uploaded don't seem to render in the plugin UI. Flagging because I can't get to look at this yet myself and I have a feeling it might be related to the type changes which are slightly out of the realms of comfort for me right now! 😁.

**Comment by neefrehman** [comment]
this might be the thing I just pushed a fix for @kemiljk? could you pull latest, rebuild and then try again

**Comment by kemiljk** [comment]
Yes it was! Fixed.
