### ISSUE TITLE
Write key

### ISSUE THREAD

**Issue by neefrehman** [kemiljk/better-logos-figma#4]
@kemiljk just bringing this over to an issue: is the write key correct? I keep getting this message when trying to push a new logo to the CMS

```shell
Not authorized. This Bucket requires the correct write access key. Find this in Bucket > Settings in your Dashboard after logging in. Read the docs for more info https://docs.cosmicjs.com
```

https://github.com/kemiljk/better-logos-figma/blob/0a4e331d8d606a8bb47dc6cf4df195352533aa7c/scripts/upload-assets.ts#L6

**Comment by kemiljk** [comment]
Odd... I think I somehow managed to revert it back (even though that's not a function in Cosmic) using undo previously I guess haha! It's now `2x1X3rPy5Rd3bB1ipl4gGIV0T2QcsuheLwh3GinJfolWXg5DaO` again. It won't change now though.

**Comment by neefrehman** [comment]
ok great, thanks @kemiljk! got things working now and have (apparently) uploaded a new logo. I can see it in the database response for all logos but not in the plugin, so I must has got some of the metadata wrong.

this is currently what I'm doing. Can you spot an issue? I couldn't find the RADIO-STRING type in the docs so maybe I'm using the wrong replacement?

Also maybe check in the CMS UI to see if what I've uploaded is even there, it's for my company (ustwo)

```js
await bucket.addObject({
        title,
        type: "logos",
        metafields: [
            {
                title,
                type: "text",
                key: "svg",
                value: fs.readFileSync(path, "utf-8")
            }
        ]
    });
```

**Comment by neefrehman** [comment]
Thanks for the info @kemiljk. I think I'm a bit closer with the below, but still a bit stumped on the file upload. From looking at the docs there's a separate endpoint for media, but it looks like we're not using that here? From the object docs it seems to be just a filename that gets passed, but I'm not sure how to reconcile that with the svg string.

Should we maybe pair up on a quick call to sort that out?

```js
await bucket.addObject({
        title,
        type: "logos",
        metafields: [
            {
                title,
                type: "text",
                key: "svg",
                value: fs.readFileSync(path, "utf-8")
            },
            {
                type: "radio-buttons",
                title: "Type",
                key: "type",
                value: "Type",
                options: [
                    { value: "Colour" },
                    { value: "Black" },
                    { value: "White" }
                ]
            },
            {
                type: "file",
                title: "Logo",
                key: "logo",
                value: filename
            },
        ]
    });
```

**Comment by kemiljk** [comment]
Sure thing, I can do that. For reference before hand, might be easier to look over this though:

https://docs.cosmicjs.com/api-reference/media#media-object

All images are stored in a folder called `logo-images` which can be access via this POST. So we could POST the images to the media endpoint then query those strings via this POST after a delay maybe?

```
const bucket = Cosmic.bucket({
  slug: 'bucket-slug',
  write_key: 'your-write-key-found-in-bucket-settings'
})

const media_object = req.files[0] // Using Multer
// OR:
// const media_object = { originalname: filename, buffer: filedata } // Not using Multer

bucket
  .addMedia({
    media: media_object,
    folder: 'logo-images',
  })
  .then(data => {
    console.log(data)
  })
  .catch(err => {
    console.log(err)
  })

// In order to pass the file `req.files.foo` to Cosmic you would do:
const media_object = {
  originalname: req.files.foo.name,
  buffer: req.files.foo.data
}
```

**Comment by neefrehman** [comment]
Ah gotcha! I didn't see the `media-object` docs. I've just updated the script and have done a successful upload. still nothing in the plugin however! Could you take a look and see what it looks like in the UI? the new object should be called ustwo2

**Comment by kemiljk** [comment]
Ahhh I see what's happened here, the SVG POST you're doing is naming the plaintext block with the SVG name when it needs to be `Svg` so it can match it with the Object model. Have corrected it below.

```
await bucket.addObject({
        title,
        type: "logos",
        metafields: [
            {
                title: "Svg",       <---- This line here
                type: "text",
                key: "svg",
                value: fs.readFileSync(path, "utf-8")
            },
            {
                type: "radio-buttons",
                title: "Type",
                key: "type",
                value: "Type",
                options: [
                    { value: "Colour" },
                    { value: "Black" },
                    { value: "White" }
                ]
            },
            {
                type: "file",
                title: "Logo",
                key: "logo",
                value: filename
            },
        ]
    });
```

<img width="677" alt="CleanShot 2021-04-28 at 16 32 20@2x" src="https://user-images.githubusercontent.com/26257029/116431382-a59f0400-a83f-11eb-907b-f4ef19038016.png">

**Comment by kemiljk** [comment]
All other fields are working perfectly in the Cosmic UI @neefrehman 👍🏻

**Comment by neefrehman** [comment]
Ah I just made another change which seemed to do the trick anyway: using the returned value from the CMS for the filename instead of the filename locally. But I'll do both :)
