### ISSUE TITLE
Sort image items by imageObject.title

### ISSUE THREAD

**Issue by kemiljk** [kemiljk/better-logos-figma#5]
To help us avoid needing to add items in alphabetical order ever.

The current endpoint returns the list sorted by creation date, which would be fine if we wanted most recent at the bottom but it means things will be out of whack as we're not going to sort them in the backend manually or upload them alphabetically.

**Comment by neefrehman** [comment]
Implemented in #7

```js
  const sortByTitle = (objects) => objects.sort((a, b) => a.title.localeCompare(b.title));
```
